_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 105
            "3":
                - 23
                - 55
            "4": 3.9.19
            "5": 0.18.2
            "6": 4.44.1
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
